[pytest]

python_files = test_*.py
python_classes = Test*
python_functions = test_*
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
console_output_style = progress
markers=
    api:接口测试
    web:ui测试
    test:测试脚本正常